Flask_Cinema_Site/movie/views.py
from Flask_Cinema_Site import db, models
from Flask_Cinema_Site.forms import SimpleForm
from Flask_Cinema_Site.movie.forms import NewMovieForm, EditMovieForm, SearchForm, SearchResultsForm
from Flask_Cinema_Site.models import Movie, Viewing
from Flask_Cinema_Site.helper_functions import save_picture, delete_picture, get_json_response
from Flask_Cinema_Site.roles import manager_permission

from flask import render_template, redirect, url_for, Blueprint, flash, request, abort, jsonify
from flask_api import status

from sqlalchemy import func, asc
from datetime import date, timedelta, datetime


movies_blueprint = Blueprint(
    'movie', __name__,
    template_folder='templates',
    static_folder='static'
)


@movies_blueprint.route('/', methods=['GET'])
def view_multiple():
    movies = Movie.query.filter_by(hidden=False).all()
    return render_template('view_multiple_movies.html', title='Browse Movies', movies=movies)


@movies_blueprint.route('/star', methods=['GET'])
def star_filter():
    movies = Movie.query.filter_by(hidden=False).all()
    return render_template('star_rating_filter.html', title='Browse Movies', movies=movies)


@movies_blueprint.route('/genre', methods=['GET'])
def genre_filter():
    movies = Movie.query.filter_by(hidden=False).all()
    return render_template('genre_filter.html', title='Browse Movies', movies=movies)


@movies_blueprint.route('/<int:movie_id>', methods=['GET'])
def view_specific(movie_id):
    m = Movie.query.get(movie_id)
    if not m:
        flash(f'Movie with id [{movie_id}] not found', 'danger')
        abort(404)

    # If hidden movie and not manager
    if m.hidden and not manager_permission.can():
        flash(f'Movie with id [{movie_id}] not found', 'danger')
        abort(404)

    viewing_days = []
    for i in range(7):
        d = date.today() + timedelta(days=i)
        viewings = Viewing.query\
            .filter(Viewing.movie_id == movie_id)\
            .filter(func.date(Viewing.time) == d)\
            .filter(Viewing.time >= datetime.now())\
            .order_by(asc(Viewing.time))\
            .all()
        viewing_days.append((d, viewings))

    return render_template('view_specific_movie.html', title=m.name, movie=m, viewing_days=viewing_days)


@movies_blueprint.route('/add', methods=['GET', 'POST'])
@manager_permission.require(status.HTTP_401_UNAUTHORIZED)
def add():
    form = NewMovieForm()
    if request.method == 'GET':
        return render_template('add_movie.html', title='Add Movie', form=form)

    if not form.validate_on_submit():
        return render_template('add_movie.html', title='Add Movie', form=form), status.HTTP_400_BAD_REQUEST

    cover_art_filename = save_picture(form.picture.data, 'movie/static/cover_arts')

    m = Movie(
        name=form.name.data,
        overview=form.overview.data,
        released=form.released.data,
        trailer=form.trailer.data,
        duration=form.duration.data,
        rating=form.rating.data,
        directors=form.directors.data,
        cast=form.cast_list.data,
        genres=form.genres.data,
        cover_art_name=cover_art_filename,
        hidden=True
    )
    db.session.add(m)
    db.session.commit()

    flash(f'Movie \'{m.name}\' added successfully', 'success')
    return redirect(url_for('movie.view_specific', movie_id=m.id))


@movies_blueprint.route('/<int:movie_id>/edit', methods=['GET', 'POST'])
@manager_permission.require(status.HTTP_401_UNAUTHORIZED)
def edit(movie_id):
    m = Movie.query.get(movie_id)
    if not m:
        flash(f'Movie with id \'{movie_id}\' does not exist', 'danger')
        abort(404)

    form = EditMovieForm()
    if request.method == 'GET':
        form.init_with_movie(m)
        return render_template('edit_movie.html', title='Edit Movie', form=form, movie=m)

    if not form.validate_on_submit():
        return render_template('edit_movie.html', title='Edit Movie', form=form, movie=m), status.HTTP_400_BAD_REQUEST

    m.name = form.name.data
    m.overview = form.overview.data
    m.released = form.released.data
    m.rating = form.rating.data
    m.directors = form.directors.data
    m.cast = form.cast_list.data
    m.genres = form.genres.data
    m.trailer = form.trailer.data

    db.session.commit()

    # Save picture / delete old one
    if form.picture.data:
        new_picture_name = save_picture(form.picture.data, 'movie', 'static', 'cover_arts')
        delete_picture('movie', 'static', 'cover_arts', m.cover_art_name)
        m.cover_art_name = new_picture_name

    flash(f'Movie \'{m.name}\' saved successfully', 'success')
    return redirect(url_for('movie.view_specific', movie_id=m.id))


# Probably should use flak-api or flask-restful idk?
@movies_blueprint.route('/hide', methods=['POST'])
@manager_permission.require(status.HTTP_401_UNAUTHORIZED)
def hide():
    form = SimpleForm()
    if not form.validate_on_submit():
        return get_json_response('Error hide movie failed', status.HTTP_400_BAD_REQUEST)

    m = Movie.query.get(form.id.data)
    if not m:
        return get_json_response(f'Movie with id \'{form.id.data}\' not found', status.HTTP_400_BAD_REQUEST)

    m.hidden = True
    db.session.commit()

    return get_json_response(f'Movie with id \'{form.id.data}\' successfully hidden', status.HTTP_200_OK)


# Probably should use flak-api or flask-restful idk?
@movies_blueprint.route('/show', methods=['POST'])
@manager_permission.require(status.HTTP_401_UNAUTHORIZED)
def show():
    form = SimpleForm()
    if not form.validate_on_submit():
        return get_json_response('Error show movie failed', status.HTTP_400_BAD_REQUEST)

    m = Movie.query.get(form.id.data)
    if not m:
        return get_json_response(f'Movie with id \'{form.id.data}\' not found', status.HTTP_400_BAD_REQUEST)

    m.hidden = False
    db.session.commit()

    return get_json_response(f'Movie with id \'{form.id.data}\' successfully unhidden', status.HTTP_200_OK)


@movies_blueprint.route('/manage', methods=['GET'])
@manager_permission.require(status.HTTP_401_UNAUTHORIZED)
def manage():
    movies = Movie.query.all()
    return render_template('manage_movie.html', title='Manage Movies', movies=movies)


@movies_blueprint.route('/search', methods=['POST'])
def search():
    form = SearchForm()
    if not form.validate_on_submit():
        return get_json_response('Search movie failed', status.HTTP_400_BAD_REQUEST)

    search_query = f'%{form.query.data}%'

    results = db.session.query(Movie.id, Movie.name).filter(
        Movie.name.like(search_query) | Movie.genres.like(search_query) | Movie.cast.like(search_query) |
        Movie.directors.like(search_query)) \
        .filter(~Movie.hidden) \
        .limit(5).all()

    movies = {m.name: m.id for m in results}
    return jsonify(movies)


@movies_blueprint.route('/search_results/')
def search_results():
    form = SearchResultsForm(request.args)
    if not form.validate_on_submit():
        pass

    search_query = f'%{form.query.data}%'

    results = db.session.query(Movie).filter(
        Movie.name.like(search_query) | Movie.genres.like(search_query) | Movie.cast.like(search_query) |
        Movie.directors.like(search_query)).filter(~Movie.hidden)\
        .all()

    return render_template('search_results.html', query=form.query.data, results=results)

Flask_Cinema_Site/movie/templates/add_movie.html
{% extends 'movies_base.html' %}

{% block content %}
    <div class="container">
        <div class="card my-4 bg-black">
            <h4 class="card-header border-bottom">Add Movie</h4>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    <fieldset class="form-groups">
                        <!-- Name -->
                        {{ get_field_group_html(form.name) }}

                        <!-- Overview -->
                        {{ get_field_group_html(form.overview) }}

                        <!-- Released -->
                        {{ get_field_group_html(form.released) }}

                        <!-- Duration -->
                        {{ get_field_group_html(form.duration) }}

                        <!-- Rating -->
                        <div class="form-group" aria-label="Review rating">
                            {{ form.rating.label(class='form-control-label') }}
                            <div>
                                {{ form.rating(class='d-none') }}
                                <!-- Rating buttons -->
                                <button id="star_1" type="button" aria-label="1 star" class="py-1 px-2 star_btn btn-dark"
                                        data-star-number="1">
                                    <i class="bi bi-star"></i></button>
                                <button id="star_2" type="button" aria-label="2 star" class="py-1 px-2 star_btn btn-dark"
                                        data-star-number="2">
                                    <i class="bi bi-star"></i></button>
                                <button id="star_3" type="button" aria-label="3 star" class="py-1 px-2 star_btn btn-dark"
                                        data-star-number="3">
                                    <i class="bi bi-star"></i></button>
                                <button id="star_4" type="button" aria-label="4 star" class="py-1 px-2 star_btn btn-dark"
                                        data-star-number="4">
                                    <i class="bi bi-star"></i></button>
                                <button id="star_5" type="button" aria-label="5 star" class="py-1 px-2 star_btn btn-dark"
                                        data-star-number="5">
                                    <i class="bi bi-star"></i></button>
                            </div>
                        </div>

                        <!-- Directors -->
                        {{ get_field_group_html(form.directors) }}

                        <!-- Cast -->
                        {{ get_field_group_html(form.cast_list) }}

                        <!-- Genre -->
                        {{ get_field_group_html(form.genres) }}

                        <!-- Movie cover art upload -->
                        {{ get_file_upload_group_html(form.picture, accept='image/png,image/jpeg') }}
                    </fieldset>
                    <!-- Submit Button -->
                    <div class="form-group">
                        {{ form.submit(class="btn btn-primary") }}
                    </div>
                    <!-- CSRF token -->
                    {{ form.csrf_token }}
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script>
        let update_stars = function (star_num) {
            // Update button colours
            $('#star_1').removeClass().addClass('py-1 px-2 star_btn btn-primary');
            $('#star_2').removeClass().addClass('py-1 px-2 star_btn btn-' + (star_num >= 2 ? 'primary' : 'dark'));
            $('#star_3').removeClass().addClass('py-1 px-2 star_btn btn-' + (star_num >= 3 ? 'primary' : 'dark'));
            $('#star_4').removeClass().addClass('py-1 px-2 star_btn btn-' + (star_num >= 4 ? 'primary' : 'dark'));
            $('#star_5').removeClass().addClass('py-1 px-2 star_btn btn-' + (star_num >= 5 ? 'primary' : 'dark'));

            // Update button stars
            $('#star_1').children('i').removeClass().addClass('bi bi-star-fill');
            $('#star_2').children('i').removeClass().addClass('bi bi-star' + (star_num >= 2 ? '-fill' : ''));
            $('#star_3').children('i').removeClass().addClass('bi bi-star' + (star_num >= 3 ? '-fill' : ''));
            $('#star_4').children('i').removeClass().addClass('bi bi-star' + (star_num >= 4 ? '-fill' : ''));
            $('#star_5').children('i').removeClass().addClass('bi bi-star' + (star_num >= 5 ? '-fill' : ''));
        }

        // Update star buttons and hidden rating value
        $('.star_btn').on('click', function () {
            let star_num = $(this).data('star-number');
            $('#rating').val(star_num);
            update_stars(star_num);
        });

        $(document).ready(function () {
            update_stars($('#rating').val());
        });
    </script>
{% endblock %}

Flask_Cinema_Site/movie/templates/genre_filter.html
{% extends 'movies_base.html' %}

{% block content %}
    <section class="jumbotron bg-transparent text-center p-0">
        <div class="container">
            <h1 class="jumbotron-heading">Browse Movies</h1>
        </div>
    </section>

    <div class="container">
        <div class="d-flex flex-row-reverse">
            <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton"
                        data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                    Sort Results
                </button>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item" href="{{ url_for('movie.star_filter') }}">Star Rating</a>
                    <a class="dropdown-item" href="{{ url_for('movie.genre_filter') }}">Genre</a>
                </div>
            </div>
        </div>
    </div>

    <div class="album py-5">
        <div class="container">
            {% for genre, movies_in_genre in movies | groupby('genres') %}
                <div class="section-line h2">{{ genre }}</div>
                <div class="card-columns">
                    {% for m in movies_in_genre %}
                        <div class="h-100">
                            {% include("snippets/movie_preview.html") %}
                        </div>
                    {% endfor %}
                </div>
            {% endfor %}

            {% if movies | length == 0 %}
                <div class="card w-100 bg-dark">
                    <div class="card-body text-center">
                        <p class="h4">No movies found</p>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>

{% endblock %}

Flask_Cinema_Site/movie/templates/manage_movie.html
{% extends 'movies_base.html' %}

{% block content %}
    <section class="jumbotron bg-transparent text-center p-0">
        <div class="container">
            <h1 class="jumbotron-heading">Manage Movies</h1>
        </div>
    </section>

    <div class="container">
        <a href="{{ url_for('movie.add') }}">
            <button class="btn btn-dark mb-3 w-100">Add new movie</button>
        </a>

        <table class="table bg-black">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Released</th>
                <th scope="col">Length (mins)</th>
                <th scope="col">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for m in movies %}
                {% include("snippets/manage_movie_preview.html") %}
            {% endfor %}
            {% if movies|length == 0 %}
                <tr>
                    <th colspan="5">No movies found</th>
                </tr>
            {% endif %}
            </tbody>
        </table>
    </div>
{% endblock %}

{% block scripts %}
    <script>
        // Show hide
        let show_movie_url = '{{ url_for('movie.show') }}';
        let hide_movie_url = '{{ url_for('movie.hide') }}';

        let show_movie = function (btn, params) {
            $.post(show_movie_url, params)
                .done(function () {
                    // Switch functionality
                    btn.removeClass('show-movie-btn');
                    btn.addClass('hide-movie-btn');
                    btn.text('Hide');
                })
                .fail(function (data) {
                    // Display error message as alert at top of page
                    if (!('responseJSON' in data) || !('msg' in data.responseJSON))
                        flash_message('Show movie failed', 'danger');
                    flash_message(data.responseJSON['msg'], 'danger');
                });
        };

        let hide_movie = function (btn, params) {
            $.post(hide_movie_url, params)
                .done(function () {
                    // Switch functionality
                    btn.removeClass('hide-movie-btn');
                    btn.addClass('show-movie-btn');
                    btn.text('Show');
                })
                .fail(function (data) {
                    // Display error message as alert at top of page
                    if (!('responseJSON' in data) || !('msg' in data.responseJSON))
                        flash_message('Show movie failed', 'danger');
                    flash_message(data.responseJSON['msg'], 'danger');
                });
        }

        // Show / hide movie
        $('.show-hide-movie-btn').on('click', function () {
            let btn = $(this);
            let params = {
                'csrf_token': '{{ simple_form.csrf_token.current_token }}',
                'id': btn.data('movie-id')
            };

            if(btn.text() === 'Show') {
                show_movie(btn, params);
            } else if (btn.text() === 'Hide') {
                hide_movie(btn, params);
            }
        });
    </script>
{% endblock %}

Flask_Cinema_Site/movie/templates/movies_base.html
{% extends 'base.html' %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('movie.static', filename='css/movies.css') }}">
{% endblock %}

Flask_Cinema_Site/movie/templates/search_results.html
{% extends 'movies_base.html' %}

{% block content %}
    <section class="jumbotron bg-transparent text-center p-0">
        <div class="container">
            <h1 class="jumbotron-heading">Search results for "{{ query }}"</h1>
        </div>
    </section>

    <div class="container">
        {% for m in results %}
            {% include 'snippets/search_result_preview.html' %}
        {% endfor %}
        {% if not results %}
            <div class="card w-100 bg-dark">
                <div class="card-body text-center">
                    <p class="h4">No results found</p>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}

{% block scripts %}

{% endblock %}

Flask_Cinema_Site/movie/templates/star_rating_filter.html
{% extends 'movies_base.html' %}

{% block content %}
    <section class="jumbotron bg-transparent text-center p-0">
        <div class="container">
            <h1 class="jumbotron-heading">Browse Movies</h1>
        </div>
    </section>

    <div class="container">
        <div class="d-flex flex-row-reverse">
            <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Sort Results
                </button>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item" href="{{ url_for('movie.star_filter') }}">Star Rating</a>
                    <a class="dropdown-item" href="{{ url_for('movie.genre_filter') }}">Genre</a>
                </div>
            </div>
        </div>
    </div>

    <div class="album py-5">
        <div class="container">
            {% for i in range(1, 6) | reverse %}
                {% if movies | selectattr('rating', 'ge', i) | selectattr('rating', 'lt', i + 1) | list | length > 0 %}
                    <div class="section-line h2">{{ i }} Star</div>
                    <div class="card-columns">
                        {% for m in movies | selectattr('rating', 'ge', i) | selectattr('rating', 'lt', i + 1) %}
                            <div class="h-100">
                                {% include("snippets/movie_preview.html") %}
                            </div>
                        {% endfor %}
                    </div>
                {% endif %}
            {% endfor %}

            {% if movies | length == 0 %}
                <div class="card w-100 bg-dark">
                    <div class="card-body text-center">
                        <p class="h4">No movies found</p>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>


{% endblock %}

Flask_Cinema_Site/movie/templates/view_multiple_movies.html
{% extends 'movies_base.html' %}

{% block content %}
    <section class="jumbotron bg-transparent text-center p-0">
        <div class="container">
            <h1 class="jumbotron-heading">Browse Movies</h1>
        </div>
    </section>

    <div class="container">
        <div class="d-flex flex-row-reverse">
            <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton"
                        data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                    Sort Results
                </button>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item" href="{{ url_for('movie.star_filter') }}">Star Rating</a>
                    <a class="dropdown-item" href="{{ url_for('movie.genre_filter') }}">Genre</a>
                    <!--<a class="dropdown-item" href="#">Date of Showing?</a>-->
                </div>
            </div>
        </div>
    </div>

    <div class="album py-5">
        <div class="container">
            {% if movies|length > 0 %}
                <div class="card-columns">
                    {% for m in movies %}
                        <div class="h-100">
                            {% include("snippets/movie_preview.html") %}
                        </div>
                    {% endfor %}
                </div>
            {% else %}
                <div class="card w-100 bg-dark">
                    <div class="card-body text-center">
                        <p class="h4">No movies found</p>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>


{% endblock %}

Flask_Cinema_Site/movie/templates/view_specific_movie.html
{% extends 'movies_base.html' %}

{% block content %}
<div class="container">
    {% if is_manager() %}
    <div id="hiddenWarning" class="alert alert-warning {{ '' if movie.hidden else 'd-none' }}">
        This movie is currently hidden
    </div>
    {% endif %}

    <div class="row mb-4">
        <!-- Cover art -->
        <div class="col-md">
            <div class="card mb-4 px-1 h-100 bg-black">
                <img class="y-100 w-100 m-auto"
                     src="{{ url_for('movie.static', filename=movie.rel_cover_art_path()) }}"
                     alt="Movie cover art">
            </div>
        </div>

        <!-- Movie Details -->
        <div class="col-md-8">
            <div class="card mb-4 box-shadow h-100 bg-black">
                <div class="card-body">
                    <h5 class="card-title">{{ movie.name }}</h5>
                    <!-- Price / Rating -->
                    <div class="d-flex justify-content-between pb-2 border-bottom">
                        <div>{{ movie.duration }} mins</div>
                        <div>
                            {{ movie.get_star_rating_html() }}
                        </div>
                    </div>
                    <p class="card-text py-2 mb-0 border-bottom">{{ movie.overview }}</p>
                    <p class="card-text py-2 mb-0 border-bottom">Release
                        date: {{ movie.released.strftime("%B %d, %Y") }}</p>
                    <p class="card-text py-2 mb-0">
                        Director: {{ movie.directors if movie.directors is not none else 'Unkown' }}</p>
                    <p class="card-text pb-2 mb-0">
                        Cast: {{ movie.cast if movie.cast is not none else 'Unkown' }}</p>
                    <p class="card-text mb-0">
                        Genres: {{ movie.genres if movie.genres is not none else 'Unkown' }}</p>
                </div>

                {% if is_manager() %}
                <!-- Edit / Hide / Delete buttons -->
                <div class="card-footer">
                    <div class="row">
                        <div class="col">
                            <a href="{{ url_for('movie.edit', movie_id=movie.id) }}"
                               class="btn btn-dark w-100">Edit movie</a>
                        </div>
                        <div class="col">
                            <button class="btn btn-primary w-100 {{ 'd-none' if movie.hidden }}"
                                    type="button" id="hideMovieBtn">Hide movie
                            </button>
                            <button class="btn btn-primary w-100 {{ 'd-none' if not movie.hidden }}"
                                    type="button" id="showMovieBtn">Show movie
                            </button>
                        </div>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
    </div>

    <!-- Viewings search -->
    <div class="card bg-black mb-4">
        <div class="card-header">Upcoming viewings</div>
        <div class="card-body">
            <div class="row mx-neg-1">
                {% for day in viewing_days %}
                <div class="col-lg col-md-12 mb-2 px-1">
                    <div class="bg-dark px-2 text-center rounded h-100">
                        <p class="h6 my-1">{{ day[0].strftime("%a %d/%m/%y") }}</p>
                        {% for v in day[1] %}
                        <div class="bg-black d-inline-block mx-auto my-1 rounded">
                            <a href="{{ url_for('bookings.view_specific', viewing_id=v.id) }}">
                                <span class="px-2 ">{{ v.time.strftime("%H:%M") }}</span>
                            </a>
                        </div>
                        {% endfor %}
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div><!-- Viewings search end -->

    <!-- Trailer -->
    <div class="card bg-black mb-4">
        <div class="card-header">Trailer</div>
        <div class="card-body">

                <div class="videoWrapper">
                    <!-- Copy & Pasted from YouTube -->
                    <iframe width="420" height="315"
                            src="{{movie.trailer}}">
                    </iframe>
                </div>

        </div>
    </div><!-- Trailer end -->

    <!-- Similar movies -->
    <div class="card bg-black">
        <div class="card-header">Similar movies you may also like</div>
        <div class="card-body">
            <div class="row">

            </div>
            {% if 0 == 0 %}
            <div class="card w-100 bg-dark">
                <div class="card-body text-center">
                    <p class="h4">No movies found</p>
                </div>
            </div>
            {% endif %}
        </div>
    </div><!-- Similar movies end -->
</div>
{% endblock %}


{% block scripts %}
{% if is_manager() %}
<script>
            let params = {
                'csrf_token': '{{ simple_form.csrf_token.current_token }}',
                'id': {{ movie.id }}
            }

            // Show hide
            let show_movie_url = '{{ url_for('movie.show') }}';
            let show_movie_btn = $('#showMovieBtn');
            let hide_movie_url = '{{ url_for('movie.hide') }}';
            let hide_movie_btn = $('#hideMovieBtn');
            let hidden_warning = $('#hiddenWarning');

            // Show movie
            show_movie_btn.on('click', function () {
                $.post(show_movie_url, params)
                    .done(function () {
                        // Hide / show buttons
                        show_movie_btn.addClass('d-none');
                        hide_movie_btn.removeClass('d-none');
                        hidden_warning.addClass('d-none');
                    })
                    .fail(function (data) {
                        // Display error message as alert at top of page
                        if (!('responseJSON' in data) || !('msg' in data.responseJSON))
                            flash_message('Show movie failed', 'danger');
                        flash_message(data.responseJSON['msg'], 'danger');
                    });
            });

            // Hide movie
            hide_movie_btn.on('click', function () {
                $.post(hide_movie_url, params)
                    .done(function () {
                        // Hide / show buttons
                        hide_movie_btn.addClass('d-none');
                        show_movie_btn.removeClass('d-none');
                        hidden_warning.removeClass('d-none');
                    })
                    .fail(function (data) {
                        // Display error message as alert at top of page
                        if (!('responseJSON' in data) || !('msg' in data.responseJSON))
                            flash_message('Hide movie failed', 'danger');
                        flash_message(data.responseJSON['msg'], 'danger');
                    });
            });


</script>
{% endif %}
{% endblock %}