Flask_Cinema_Site/user/views.py
from Flask_Cinema_Site import app, db, models, helper_functions
from Flask_Cinema_Site.models import User, Role
from Flask_Cinema_Site.helper_functions import get_redirect_url
from Flask_Cinema_Site.forms import SimpleForm
from .forms import LoginForm, SignupForm, ForgotPasswordForm, ResetPasswordForm, \
    ChangePasswordForm, ChangeDetailsForm

from flask import render_template, Blueprint, flash, redirect, url_for, request, current_app, session
from flask_login import LoginManager, login_user, logout_user, current_user, login_required
from flask_api import status
from flask_principal import identity_changed, Identity, AnonymousIdentity

from datetime import datetime

user_blueprint = Blueprint(
    'user', __name__,
    template_folder='templates'
)

login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_view = 'user.login'


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


def send_password_reset_email(user):
    token = user.get_reset_password_token()
    helper_functions.send_email(
        subject='[Microblog] Reset Your Password',
        sender=app.config['MAIL_USERNAME'],
        recipients=[user.email],
        text_body=render_template('email/reset_password_body.txt', user=user, token=token),
        html_body=render_template('email/reset_password_body.html', user=user, token=token)
    )


@app.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_password(token):
    u = User.verify_reset_password_token(token)
    if not u:
        flash('Invalid reset password link', 'danger')
        return redirect(get_redirect_url())

    form = ResetPasswordForm()
    if not form.validate_on_submit():
        return render_template('reset_password.html', form=form)

    u.set_password(form.password.data)
    db.session.commit()

    flash('Password updated successfully', 'success')
    return redirect(url_for('user.login_get'))


@user_blueprint.route('/forgot_password', methods=['GET', 'POST'])
def forgot_password():
    # Check if user logged in
    if current_user.is_authenticated:
        return redirect(get_redirect_url())

    form = ForgotPasswordForm()
    if request.method == 'GET':
        return render_template('forgot_password.html', title='Reset password', form=form)

    if not form.validate_on_submit():
        return render_template('forgot_password.html', title='Reset password', form=form), status.HTTP_400_BAD_REQUEST

    u = db.session.query(models.User).filter_by(email=form.email.data).first()
    if not u:
        flash('Unknown email has been entered.', 'danger')
        return render_template('forgot_password.html', title='Reset password', form=form)

    send_password_reset_email(u)
    flash('A link has been sent to your email to reset your password, the link will expire after 24 hours.', 'success')
    return render_template('forgot_password.html', title='Reset password', form=form)


@user_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    # Check if user logged in
    if current_user.is_authenticated:
        return redirect(get_redirect_url())

    form = LoginForm()
    if request.method == 'GET':
        return render_template('login.html', title='Login', form=form)

    # Validate form submission
    if not form.validate_on_submit():
        return render_template('login.html', title='Login', form=form), status.HTTP_400_BAD_REQUEST

    # Check for user
    u = User.query.filter_by(email=form.email.data).first()
    if not u or not u.check_password(form.password.data):
        flash('Login failed. Provided details were incorrect.', 'danger')
        return render_template('login.html', title='Login', form=form), status.HTTP_400_BAD_REQUEST

    # Update last login date time
    u.last_login = datetime.now()
    db.session.commit()

    # Login successful
    login_user(u, form.remember.data)
    # Tell Flask-Principal the identity changed
    identity_changed.send(current_app._get_current_object(), identity=Identity(u.id))

    flash('Login successful', 'success')
    return redirect(get_redirect_url())


@user_blueprint.route('/signup', methods=['GET', 'POST'])
def signup():
    # Check if user logged in
    if current_user.is_authenticated:
        return redirect(get_redirect_url())

    form = SignupForm()
    if request.method == 'GET':
        return render_template('signup.html', title='Sign Up', form=form)

    if not form.validate_on_submit():
        return render_template('signup.html', title='Sign Up', form=form), status.\
            HTTP_400_BAD_REQUEST

    new_user = models.User(first_name=form.first_name.data,
                           last_name=form.last_name.data,
                           username=form.username.data,
                           email=form.email.data,
                           confirmed=False)
    new_user.set_password(form.password.data)

    # Add user as customer
    customer_role = Role.query.filter_by(name='customer').first()
    customer_role.users.append(new_user)
    db.session.commit()

    # Generate and send confirmation email
    token = new_user.get_email_confirm_token()
    confirm_url = url_for('user.confirm_email', token=token, _external=True)

    helper_functions.send_email(
        subject='Confirm your account',
        sender=app.config['MAIL_USERNAME'],
        recipients=[new_user.email],
        text_body=render_template('email/confirm_email_body.txt', confirm_url=confirm_url),
        html_body=render_template('email/confirm_email_body.html', confirm_url=confirm_url)
    )

    flash(f'New user \'{new_user.username}\' was successfully created', 'success')
    return redirect(url_for('user.login'))


@user_blueprint.route('/confirm/<token>')
def confirm_email(token):
    u = User.verify_email_confirm_token(token)
    if u.confirmed:
        flash("Account already confirmed.", "danger")
        return redirect(url_for('home.home'))

    u.confirmed = True
    db.session.commit()
    flash(f'User \'{u.username}\' has been successfully confirmed', "success")
    return redirect(url_for('home.home'))


@login_required
@user_blueprint.route('/activate')
def activate():
    return render_template('verify_account.html')


@login_required
@user_blueprint.route('/resend')
def resend():
    # Generate and send confirmation email
    token = current_user.get_email_confirm_token()
    confirm_url = url_for('user.confirm_email', token=token, _external=True)
    helper_functions.send_email(
        subject='Confirm your account',
        sender=app.config['MAIL_USERNAME'],
        recipients=[current_user.email],
        text_body=render_template('email/confirm_email_body.txt', confirm_url=confirm_url),
        html_body=render_template('email/confirm_email_body.html', confirm_url=confirm_url)
    )
    flash("Activation link sent!", "warning")
    return redirect(url_for('user.activate'))


@user_blueprint.route('/logout', methods=['POST'])
def logout():
    if not current_user.is_authenticated:
        flash('Logout failed. No user logged in', 'danger')
        return redirect(get_redirect_url())

    form = SimpleForm()
    del form.id
    if not form.validate_on_submit():
        flash('Logout failed', 'danger')
        return redirect(url_for('home.home'))

    # Remove session keys set by Flask-Principal
    for key in ('identity.name', 'identity.auth_type'):
        session.pop(key, None)

    # Tell Flask-Principal the user is anonymous
    identity_changed.send(current_app._get_current_object(), identity=AnonymousIdentity())

    logout_user()
    flash('Logout successful', 'success')
    return redirect(url_for('home.home'))


def render_manage_user(change_details_form=None, change_password_form=None,
                       res_status=status.HTTP_200_OK):
    if change_details_form is None:
        change_details_form = ChangeDetailsForm()
        # Initialize form
        change_details_form.first_name.data = current_user.first_name
        change_details_form.last_name.data = current_user.last_name
        change_details_form.username.data = current_user.username
        change_details_form.email.data = current_user.email
    if change_password_form is None:
        change_password_form = ChangePasswordForm()

    return render_template('manage_user.html', title='Manage Account',
                           details_form=change_details_form,
                           password_form=change_password_form), res_status


@user_blueprint.route('/manage')
@login_required
# @check_confirmed if user makes mistake in email they cant fix it if they are required to confirm it first
def manage():
    return render_manage_user()


@user_blueprint.route('/manage/update_user_details', methods=['POST'])
@login_required
def update_user_details():
    form = ChangeDetailsForm()

    # Validate submitted details
    if not form.validate_on_submit():
        return render_manage_user(change_details_form=form, res_status=status.HTTP_400_BAD_REQUEST)

    # Update details
    current_user.confirmed = current_user.confirmed and current_user.email == form.email.data
    current_user.first_name = form.first_name.data
    current_user.last_name = form.last_name.data
    current_user.username = form.username.data
    current_user.email = form.email.data
    db.session.commit()

    flash('Details successfully updated', 'success')

    return render_manage_user(change_details_form=form)


@user_blueprint.route('/manage/change_password', methods=['POST'])
@login_required
def change_password():
    form = ChangePasswordForm()

    if not form.validate_on_submit():
        return render_manage_user(change_password_form=form, res_status=status.HTTP_400_BAD_REQUEST)

    # Update password
    current_user.set_password(form.password.data)
    db.session.commit()
    flash('Password updated successfully', 'success')
    return render_manage_user(change_password_form=form)

Flask_Cinema_Site/user/templates/forgot_password.html
{% extends 'user_base.html' %}

{% block content %}
    <div class="container">
        <div class="card bg-black">
            <h4 class="card-header border-bottom">Request reset password</h4>

            <div class="card-body">
                <form action="" method="post">
                    <!-- Email -->
                    <div class="form-group">
                        {{ get_field_html(form.email) }}
                        <small id="emailHelp" class="form-text text-muted">We'll never share your
                            email with anyone else.</small>
                    </div>

                    <!-- Submit Button -->
                    <div class="form-group">
                        {{ form.submit(class="btn btn-primary") }}
                    </div>

                    {{ form.hidden_tag() }}
                </form>
                <div class="border-top pt-2">
                    <small class="text-muted">
                        Return to <a class="ml-1" href="{{ url_for('user.login') }}">login</a>
                    </small>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Flask_Cinema_Site/user/templates/login.html
{% extends 'user_base.html' %}

{% block content %}
    <div class="container">
        <div class="card bg-black">
            <h4 class="card-header border-bottom">Login</h4>

            <div class="card-body">
                <form action="" method="post">
                    <fieldset class="form-groups">
                        <!-- Email -->
                        {{ get_field_group_html(form.email) }}

                        <!-- Password -->
                        {{ get_field_group_html(form.password) }}

                        <!-- Remember Me -->
                        <div class="form-group form-check">
                            {{ form.remember(class="form-check-input") }}
                            {{ form.remember.label(class="form-check-label") }}
                        </div>
                    </fieldset>

                    <!-- Submit Button -->
                    <div class="form-group">
                        {{ form.login_btn(class="btn btn-primary d-block") }}
                        <small class="text-muted">
                            <a class="ml-1" href="{{ url_for('user.forgot_password') }}">Forgot password</a>
                        </small>
                    </div>

                    {{ form.hidden_tag() }}
                </form>
                <div class="border-top pt-2">
                    <small class="text-muted">
                        Not got an account? <a class="ml-1" href="{{ url_for('user.signup') }}">Register
                        Now</a>
                    </small>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Flask_Cinema_Site/user/templates/manage_user.html
{% extends 'user_base.html' %}

{% block content %}
    <div class="container">
        <!-- Update Details -->
        <div class="card bg-black my-4">
            <h4 class="card-header border-bottom">Update Details</h4>
            <div class="card-body">
                <form method="post" action="{{ url_for('user.update_user_details') }}">
                    <fieldset class="form-groups">
                        <!-- First name -->
                        {{ get_field_group_html(details_form.first_name) }}

                        <!-- Last name -->
                        {{ get_field_group_html(details_form.last_name) }}

                        <!-- Username -->
                        {{ get_field_group_html(details_form.username) }}

                        <!-- Email -->
                        {{ get_field_group_html(details_form.email) }}
                    </fieldset>
                    <!-- Save Button -->
                    <div class="form-group">
                        {{ details_form.submit(class="btn btn-dark", id="change_details_submit") }}
                    </div>
                    <!-- CSRF token -->
                    {{ details_form.csrf_token(id="changeDetailsCsrfToken") }}
                </form>
            </div>
        </div>

        <!-- Change Password -->
        <div class="card bg-black my-4">
            <h4 class="card-header border-bottom">Change Password</h4>
            <div class="card-body">
                <form method="post" action="{{ url_for('user.change_password') }}">
                    <fieldset class="form-groups">
                        <!-- Current Password -->
                        {{ get_field_group_html(password_form.current_password) }}

                        <!-- New Password -->
                        {{ get_field_group_html(password_form.password) }}

                        <!-- New Password Confirm -->
                        {{ get_field_group_html(password_form.password_confirm) }}
                    </fieldset>
                    <!-- Save Button -->
                    <div class="form-group">
                        {{ password_form.submit(class="btn btn-dark", id="change_password_submit") }}
                    </div>
                    <!-- CSRF token -->
                    {{ password_form.csrf_token(id="changePasswordCsrfToken") }}
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block end_of_page %}
    <script>
        let password_field = $('#{{ password_form.password.id }}')
        let password_confirm_field = $('#{{ password_form.password_confirm.id }}')

        $('form').submit(function (event) {
            if (password_field.val() !== password_confirm_field.val()) {
                event.preventDefault();
                if (!password_confirm_field.attr('class').includes('is-invalid')) {
                    password_confirm_field.nextAll('.invalid-feedback:first')
                        .append('<p class="mb-0">Passwords must match.</p>');
                    password_confirm_field.addClass('is-invalid');
                }
            }
        });
    </script>
{% endblock %}

Flask_Cinema_Site/user/templates/reset_password.html
{% extends "user_base.html" %}

{% block content %}
    <div class="container">
        <div class="card bg-black">
            <h4 class="card-header border-bottom">Reset Your Password</h4>

            <div class="card-body">
                <form action="" method="post">
                    {{ form.hidden_tag() }}
                    <fieldset class="form-groups">
                        <!-- Password -->
                        {{ get_field_group_html(form.password) }}

                        <!-- Confirm password -->
                        {{ get_field_group_html(form.password2) }}
                    </fieldset>
                    <!-- Submit Button -->
                    <div class="form-group">
                        {{ form.submit(class="btn btn-primary d-block") }}
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

Flask_Cinema_Site/user/templates/signup.html
{% extends 'user_base.html' %}

{% block content %}
    <div class="container">
        <div class="card bg-black">
            <h4 class="card-header border-bottom">Register</h4>

            <div class="card-body">
                <form action="" method="post">
                    <fieldset class="form-groups">
                        <!-- Names -->
                        <div class="form-row">
                            <div class="form-group col">
                                {{ get_field_html(form.first_name) }}
                            </div>
                            <div class="form-group col">
                                {{ get_field_html(form.last_name) }}
                            </div>
                        </div>

                        <!-- Email / username -->
                        <div class="form-row">
                            <div class="form-group col">
                                {{ get_field_html(form.email) }}
                            </div>
                            <div class="form-group col-md-4">
                                {{ form.username.label(class="form-control-label") }}
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">@</span>
                                    </div>
                                    {% if form.username.errors %}
                                        {{ form.username(class='form-control is-invalid') }}
                                    {% else %}
                                        {{ form.username(class='form-control') }}
                                    {% endif %}
                                </div>
                                {{ get_file_upload_errors_html(form.username.errors) }}
                            </div>
                        </div>

                        <!-- Passwords -->
                        <div class="form-row">
                            <div class="form-group col">
                                {{ get_field_html(form.password) }}
                            </div>
                            <div class="form-group col">
                                {{ get_field_html(form.password_confirm) }}
                            </div>
                        </div>

                        <!-- Consent -->
                        <div class="form-group form-check">
                            {{ form.consent(class="form-check-input") }}
                            {{ form.consent.label(class="form-check-label") }}
                        </div>
                    </fieldset>

                    <!-- Submit Button -->
                    <div class="form-group">
                        {{ form.signup_btn(class="btn btn-primary d-block") }}
                    </div>

                    {{ form.hidden_tag() }}
                </form>
                <div class="border-top pt-2">
                    <small class="text-muted">
                        Already have an account? <a class="ml-1" href="{{ url_for('user.login') }}">Login</a>
                    </small>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Flask_Cinema_Site/user/templates/user_base.html
{% extends 'base.html' %}