Flask_Cinema_Site/bookings/forms.py
from Flask_Cinema_Site.models import Seat, SavedCard

from flask_login import current_user
from flask_wtf import FlaskForm

from wtforms import StringField, PasswordField, SubmitField, HiddenField, BooleanField
from wtforms.fields.html5 import EmailField, DateField
from wtforms.validators import DataRequired, Length, Email, ValidationError

import json


class BasePaymentForm(FlaskForm):
    seats_json = HiddenField('Selected Seats', validators=[DataRequired()])

    def validate_seats_json(self, seats_json):
        seats = json.loads(self.seats_json.data)

        for seat_num, ticket_type in seats:
            if not Seat.is_number_type_valid(seat_num, ticket_type):
                raise ValidationError(f'Seat \'{seat_num}\' with type \'{ticket_type}\' is invalid')


class CashPaymentForm(BasePaymentForm):
    customer_email = EmailField('Customer email', validators=[DataRequired(), Email()])
    submit = SubmitField('Accept payment and book')


class CardPaymentForm(BasePaymentForm):
    card = StringField('Card', validators=[DataRequired(), Length(min=16, max=19)])
    cvc = PasswordField('CVC', validators=[DataRequired()])
    expiry = DateField('Expiry date')
    remember = BooleanField('Remember card')
    submit = SubmitField('Pay')

    def validate_card(self, card_number):
        if not self.card.data.startswith('****'):
            return

        last_4_digits = self.card.data[-4:]
        saved_card = SavedCard.query\
            .filter(SavedCard.user_id == current_user.id)\
            .filter(SavedCard.number.like(f'%{last_4_digits}'))\
            .first()
        if not saved_card:
            raise ValidationError(f'Card ending \'{last_4_digits}\' not found')

Flask_Cinema_Site/bookings/views.py
from flask import render_template, redirect, Blueprint, flash, send_file
from flask_login import current_user, login_required

from Flask_Cinema_Site import db
from Flask_Cinema_Site.roles import manager_permission
from Flask_Cinema_Site.models import Viewing, Transaction, TicketType, SavedCard, Seat
from Flask_Cinema_Site.helper_functions import get_redirect_url
from Flask_Cinema_Site.bookings.forms import CardPaymentForm, CashPaymentForm
from Flask_Cinema_Site.bookings.helper_functions import generate_receipt_pdf

import json
from datetime import datetime, date
from sqlalchemy import func
from pathlib import Path

bookings_blueprint = Blueprint(
    'bookings', __name__,
    template_folder='templates',
    static_folder='static'
)


def make_booking_email_receipt_redirect(v: Viewing, seats_json, cash_payment_form=None, card_payment_form=None):
    seats = json.loads(seats_json)
    new_transaction, msg = v.book_seats(seats, current_user)
    if not new_transaction:
        flash(msg, 'danger')
        return render_book_specific_viewing(v, cash_payment_form=cash_payment_form, card_payment_form=card_payment_form)

    email_address = current_user.email
    if cash_payment_form:
        email_address = cash_payment_form.customer_email.data

    generate_receipt_pdf(new_transaction, email_address)

    return render_template('transaction_complete.html', transaction=new_transaction)


def get_validate_viewing(viewing_id):
    v = Viewing.query.get(viewing_id)
    if not v:
        flash(f'Viewing with id [{viewing_id}] not found', 'danger')

    # Check viewing in the future and not hidden
    if v.time < datetime.now() and not v.movie.hidden:
        flash(f'Viewing with id [{viewing_id}] not found', 'danger')
        return None

    return v


def render_book_specific_viewing(v: Viewing, cash_payment_form: CashPaymentForm = None,
                                 card_payment_form: CardPaymentForm = None):
    if not cash_payment_form:
        cash_payment_form = CashPaymentForm()
    if not card_payment_form:
        card_payment_form = CardPaymentForm()

    ticket_prices = {t.name.lower(): t.price for t in TicketType.query.all()}
    return render_template('select_time.html', title=v.movie.name, viewing=v, cash_payment_form=cash_payment_form,
                           card_payment_form=card_payment_form, ticket_prices=ticket_prices,
                           is_seat_available=v.is_seat_available)


@bookings_blueprint.route('/viewing/<int:viewing_id>', methods=['GET'])
@login_required
def view_specific(viewing_id):
    v = get_validate_viewing(viewing_id)
    if not v:
        return redirect(get_redirect_url())

    cash_payment_form = CashPaymentForm()
    return render_book_specific_viewing(v, cash_payment_form=cash_payment_form)


@bookings_blueprint.route('/viewing/<int:viewing_id>/pay/cash', methods=['POST'])
@manager_permission.require(401)
def book_with_cash(viewing_id):
    v = get_validate_viewing(viewing_id)
    if not v:
        return redirect(get_redirect_url())

    cash_payment_form = CashPaymentForm()
    if not cash_payment_form.validate_on_submit():
        if cash_payment_form.seats_json.errors:
            flash(cash_payment_form.seats_json.errors[0], 'danger')
        return render_book_specific_viewing(v, cash_payment_form=cash_payment_form)

    return make_booking_email_receipt_redirect(v, cash_payment_form.seats_json.data,
                                               cash_payment_form=cash_payment_form)


@bookings_blueprint.route('/viewing/<int:viewing_id>/pay/card', methods=['POST'])
@login_required
def book_with_card(viewing_id):
    v = get_validate_viewing(viewing_id)
    if not v:
        return redirect(get_redirect_url())

    card_payment_form = CardPaymentForm()
    if not card_payment_form.validate_on_submit():
        if card_payment_form.seats_json.errors:
            flash(card_payment_form.seats_json.errors[0], 'danger')
        return render_book_specific_viewing(v, card_payment_form=card_payment_form)

    # Process card payment

    if card_payment_form.remember:
        # Check card not already saved
        last_4_digits = card_payment_form.card.data[-4:]
        saved_card = SavedCard.query \
            .filter(SavedCard.user_id == current_user.id) \
            .filter(SavedCard.number.like(f'%{last_4_digits}')) \
            .first()

        if not saved_card:
            current_user.saved_cards.append(SavedCard(
                number=card_payment_form.card.data,
                expiry=card_payment_form.expiry.data
            ))
            db.session.commit()

    return make_booking_email_receipt_redirect(v, card_payment_form.seats_json.data,
                                               card_payment_form=card_payment_form)


@bookings_blueprint.route('/upcoming', methods=['GET'])
@login_required
def my_upcoming_bookings():
    transactions = Transaction.query \
        .join(Transaction.viewings) \
        .filter(func.date(Viewing.time) >= date.today()) \
        .filter(Transaction.user_id == current_user.id) \
        .order_by(func.date(Viewing.time)) \
        .all()

    return render_template('my_bookings.html', title='Upcoming bookings', transactions=transactions, show_all_btn=True)


@bookings_blueprint.route('/all', methods=['GET'])
@login_required
def my_bookings():
    transactions = Transaction.query \
        .join(Transaction.viewings) \
        .filter(Transaction.user_id == current_user.id) \
        .order_by(func.date(Viewing.time)) \
        .all()
    return render_template('my_bookings.html', title='All bookings', transactions=transactions)


@bookings_blueprint.route('/receipt/<int:transaction_id>', methods=['GET'])
@login_required
def view_receipt(transaction_id):
    t = Transaction.query.filter_by(id=transaction_id, user_id=current_user.id).first()
    if not t:
        flash(f'Transaction with id \'{transaction_id}\' not found', 'danger')
        return redirect(get_redirect_url())

    path = t.get_receipt_path()
    if not Path(path).is_file():
        flash('Receipt not found', 'danger')
        return redirect(get_redirect_url())

    return send_file(path, attachment_filename='tickets.pdf')


@bookings_blueprint.route('/cancel/<int:transaction_id>', methods=['GET'])
@login_required
def cancel(transaction_id):
    t = Transaction.query.filter_by(id=transaction_id, user_id=current_user.id).first()
    if not t:
        flash(f'Transaction with id \'{transaction_id}\' not found', 'danger')
        return redirect(get_redirect_url())

    db.session.delete(t)
    db.session.commit()

    return render_template('canceled_booking.html', title='Cancelled')

Flask_Cinema_Site/bookings/templates/booking_base.html
{% extends 'base.html' %}

Flask_Cinema_Site/bookings/templates/canceled_booking.html
{% extends 'booking_base.html' %}

{% block content %}
<section class="jumbotron bg-transparent text-center p-0 text-success">
    <div class="container">
        <h1 class="jumbotron-heading">Booking Cancelled</h1>
    </div>
</section>
<div class="container">
    <div class="row justify-content-center">
        <h2>Hope to see you again soon!</h2>
    </div>

    <div class="row justify-content-center">
        <a href="{{url_for('home.home')}}"><h2>Return Home</h2></a>
    </div>
</div>
{% endblock %}

{% block scripts %}

{% endblock %}

Flask_Cinema_Site/bookings/templates/my_bookings.html
{% extends 'booking_base.html' %}

{% block content %}
    <section class="jumbotron bg-transparent text-center p-0">
        <div class="container">
            <h1 class="jumbotron-heading">{{ title }}</h1>
        </div>
    </section>

    <div class="container">
        {% if show_all_btn %}
            <a href="{{ url_for('bookings.my_bookings') }}">
                <button class="btn btn-dark mb-3 w-100">Show all bookings</button>
            </a>
        {% else %}
            <a href="{{ url_for('bookings.my_upcoming_bookings') }}">
                <button class="btn btn-dark mb-3 w-100">Show upcoming bookings</button>
            </a>
        {% endif %}

        {% for t in transactions %}
            {% include 'snippets/booking_preview.html' %}
        {% endfor %}
        {% if not transactions %}
            <div class="card w-100 bg-dark">
                <div class="card-body text-center">
                    <p class="h4">No bookings found</p>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}

{% block scripts %}

{% endblock %}

Flask_Cinema_Site/bookings/templates/snippets/booking_preview.html
{% with %}
    {% set v = t.viewings[0] %}
    {% set m = v.movie %}

    <div class="card bg-black mb-4">
        <div class="card-body row">
            <div class="col-lg-2 col-md-4 text-center m-1">
                <a href="{{ url_for('movie.view_specific', movie_id=m.id) }}">
                    <img class="img-fluid" src="{{ url_for('movie.static', filename=m.rel_cover_art_path()) }}" alt="{{ m.name }} covert art">
                </a>
            </div>

            <div class="col-lg col-md m-1">
                <p class="h3"><a href="{{ url_for('movie.view_specific', movie_id=m.id) }}">{{ m.name }}</a></p>
                <div class="d-flex justify-content-between border-bottom pb-2 mb-2">
                    <div>{{ m.duration }} mins</div>
                    <div>
                        {{ m.get_star_rating_html() }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-xl col-md-6 mb-3">
                        <p class="h5">Seats:</p>
                        {% for seat in t.seats %}
                            <p class="mb-0">{{ seat.seat_number }} - {{ seat.ticket_type.name }}</p>
                        {% endfor %}
                    </div>
                    <div class="col-xl col-md-6 mb-3">
                        <p class="h5">Viewing details:</p>
                        <p class="mb-0">Time: {{ v.time.strftime('%H:%M') }}</p>
                        <p class="mb-0">Date: {{ v.time.strftime('%d/%m') }}</p>
                        <p class="mb-0">Screen: {{ v.screen.name}}</p>
                    </div>
                    <div class="col-xl-6 col-md-12">
                        <p class="h5">Transaction details:</p>
                        <div class="row">
                            <div class="col">
                                <p class="mb-0">Time: {{ t.datetime.strftime('%H:%M') }}</p>
                                <p>Date: {{ t.datetime.strftime('%d/%m') }}</p>
                                <a href="{{ url_for('bookings.cancel', transaction_id=t.id) }}">
                                    <button class="btn btn-danger">Cancel Booking</button>
                                </a>
                            </div>
                            <div class="col">
                                <p class="mb-0">VAT: £{{ '%.2f' | format(t.get_cost() * 0.2) }}</p>
                                <p>Total cost: £{{ '%.2f' | format(t.get_cost()) }}</p>
                                <a href="{{ url_for('bookings.view_receipt', transaction_id=t.id) }}" target="_blank">
                                    <button class="btn btn-success">View receipt</button>
                                </a>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>

{% endwith %}

Flask_Cinema_Site/bookings/templates/snippets/select_seat_popover.html
<div class="form-check">
    <input class="form-check-input ticket_type_radio" type="radio" name="ticketTypeRadio" id="availableRadio"
           value="available">
    <label class="form-check-label" for="availableRadio">
        Available
    </label>
</div>

<div class="form-check">
    <input class="form-check-input ticket_type_radio" type="radio" name="ticketTypeRadio" id="childRadio" value="child">
    <label class="form-check-label" for="childRadio">
        Child - {{ '£%.2f' | format(ticket_prices.child) }}
    </label>
</div>

<div class="form-check">
    <input class="form-check-input ticket_type_radio" type="radio" name="ticketTypeRadio" id="seniorRadio" value="senior">
    <label class="form-check-label" for="seniorRadio">
        Senior - {{ '£%.2f' | format(ticket_prices.senior) }}
    </label>
</div>

<div class="form-check">
    <input class="form-check-input ticket_type_radio" type="radio" name="ticketTypeRadio" id="adultRadio" value="adult">
    <label class="form-check-label" for="adultRadio">
        Adult - {{ '£%.2f' | format(ticket_prices.adult) }}
    </label>
</div>

Flask_Cinema_Site/bookings/templates/snippets/select_seat_popover_vip.html
<div class="form-check">
    <input class="form-check-input ticket_type_radio" type="radio" name="ticketTypeRadio" id="availableRadioVip"
           value="available">
    <label class="form-check-label" for="availableRadioVip">
        Available
    </label>
</div>

<div class="form-check">
    <input class="form-check-input ticket_type_radio" type="radio" name="ticketTypeRadio" id="vipRadio" value="vip">
    <label class="form-check-label" for="vipRadio">
        VIP - {{ '£%.2f' | format(ticket_prices.vip) }}
    </label>
</div>

Flask_Cinema_Site/bookings/templates/snippets/select_seats_row.html
<tr>
    <td>
        <span class="h5">{{ char }}</span>
    </td>
    <td>
        <button type="button"
                class="btn btn-info seat-btn {{ 'seat-available' if is_seat_available(char ~ 1) else 'seat-booked disabled' }}"
                id="{{ char }}1">1
        </button>
    </td>
    <td>
        <button type="button"
                class="btn btn-info seat-btn {{ 'seat-available' if is_seat_available(char ~ 2) else 'seat-booked disabled' }}"
                id="{{ char }}2">2
        </button>
    </td>
    <td><span class="mx-1"></span></td>
    {% for i in range(3, 8) %}
        <td>
            <button type="button"
                    class="btn btn-info seat-btn {{ 'seat-available' if is_seat_available(char ~ i) else 'seat-booked disabled' }}"
                    id="{{ char }}{{ i }}">{{ i }}</button>
        </td>
    {% endfor %}
    <td><span class="mx-1"></span></td>
    <td>
        <button type="button"
                class="btn btn-info seat-btn {{ 'seat-available' if is_seat_available(char ~ 8) else 'seat-booked disabled' }}"
                id="{{ char }}8">8
        </button>
    </td>
    <td>
        <button type="button"
                class="btn btn-info seat-btn {{ 'seat-available' if is_seat_available(char ~ 9) else 'seat-booked disabled' }}"
                id="{{ char }}9">9
        </button>
    </td>
    <td>
        <span class="h5">{{ char }}</span>
    </td>
</tr>

Flask_Cinema_Site/bookings/templates/transaction_complete.html
{% extends 'booking_base.html' %}

{% block content %}
<section class="jumbotron bg-transparent text-center p-0 text-success">
    <div class="container">
        <h1 class="jumbotron-heading">Transaction Successful!</h1>
    </div>
</section>
<div class="container">
    <div class="row">
        <h2>You're going to See:</h2>
    </div>
    <div class="row pb-5">
        <div class="container">
            {% set t = transaction %}
            {% include 'snippets/booking_preview.html' %}
        </div>
    </div>


    <div class="row justify-content-center pt-5">
        <h2>You should receive an email receipt soon. </h2>
    </div>
    <div class="row justify-content-center">
        <a href="{{url_for('home.home')}}"><h2>Return Home</h2></a>
    </div>
    <div class="row justify-content-center pt-5">
        <a href="{{ url_for('bookings.cancel', transaction_id=t.id) }}"><p>Cancel Transaction?</p></a>
    </div>
</div>
{% endblock %}

{% block scripts %}

{% endblock %}