Flask_Cinema_Site/movie/views.py
from Flask_Cinema_Site import db, models
from Flask_Cinema_Site.forms import SimpleForm
from Flask_Cinema_Site.movie.forms import NewMovieForm, EditMovieForm, SearchForm, SearchResultsForm
from Flask_Cinema_Site.models import Movie, Viewing
from Flask_Cinema_Site.helper_functions import save_picture, delete_picture, get_json_response
from Flask_Cinema_Site.roles import manager_permission

from flask import render_template, redirect, url_for, Blueprint, flash, request, abort, jsonify
from flask_api import status

from sqlalchemy import func, asc
from datetime import date, timedelta, datetime


movies_blueprint = Blueprint(
    'movie', __name__,
    template_folder='templates',
    static_folder='static'
)


@movies_blueprint.route('/', methods=['GET'])
def view_multiple():
    movies = Movie.query.filter_by(hidden=False).all()
    return render_template('view_multiple_movies.html', title='Browse Movies', movies=movies)


@movies_blueprint.route('/star', methods=['GET'])
def star_filter():
    movies = Movie.query.filter_by(hidden=False).all()
    return render_template('star_rating_filter.html', title='Browse Movies', movies=movies)


@movies_blueprint.route('/genre', methods=['GET'])
def genre_filter():
    movies = Movie.query.filter_by(hidden=False).all()
    return render_template('genre_filter.html', title='Browse Movies', movies=movies)


@movies_blueprint.route('/<int:movie_id>', methods=['GET'])
def view_specific(movie_id):
    m = Movie.query.get(movie_id)
    if not m:
        flash(f'Movie with id [{movie_id}] not found', 'danger')
        abort(404)

    # If hidden movie and not manager
    if m.hidden and not manager_permission.can():
        flash(f'Movie with id [{movie_id}] not found', 'danger')
        abort(404)

    viewing_days = []
    for i in range(7):
        d = date.today() + timedelta(days=i)
        viewings = Viewing.query\
            .filter(Viewing.movie_id == movie_id)\
            .filter(func.date(Viewing.time) == d)\
            .filter(Viewing.time >= datetime.now())\
            .order_by(asc(Viewing.time))\
            .all()
        viewing_days.append((d, viewings))

    return render_template('view_specific_movie.html', title=m.name, movie=m, viewing_days=viewing_days)


@movies_blueprint.route('/add', methods=['GET', 'POST'])
@manager_permission.require(status.HTTP_401_UNAUTHORIZED)
def add():
    form = NewMovieForm()
    if request.method == 'GET':
        return render_template('add_movie.html', title='Add Movie', form=form)

    if not form.validate_on_submit():
        return render_template('add_movie.html', title='Add Movie', form=form), status.HTTP_400_BAD_REQUEST

    cover_art_filename = save_picture(form.picture.data, 'movie/static/cover_arts')

    m = Movie(
        name=form.name.data,
        overview=form.overview.data,
        released=form.released.data,
        trailer=form.trailer.data,
        duration=form.duration.data,
        rating=form.rating.data,
        directors=form.directors.data,
        cast=form.cast_list.data,
        genres=form.genres.data,
        cover_art_name=cover_art_filename,
        hidden=True
    )
    db.session.add(m)
    db.session.commit()

    flash(f'Movie \'{m.name}\' added successfully', 'success')
    return redirect(url_for('movie.view_specific', movie_id=m.id))


@movies_blueprint.route('/<int:movie_id>/edit', methods=['GET', 'POST'])
@manager_permission.require(status.HTTP_401_UNAUTHORIZED)
def edit(movie_id):
    m = Movie.query.get(movie_id)
    if not m:
        flash(f'Movie with id \'{movie_id}\' does not exist', 'danger')
        abort(404)

    form = EditMovieForm()
    if request.method == 'GET':
        form.init_with_movie(m)
        return render_template('edit_movie.html', title='Edit Movie', form=form, movie=m)

    if not form.validate_on_submit():
        return render_template('edit_movie.html', title='Edit Movie', form=form, movie=m), status.HTTP_400_BAD_REQUEST

    m.name = form.name.data
    m.overview = form.overview.data
    m.released = form.released.data
    m.rating = form.rating.data
    m.directors = form.directors.data
    m.cast = form.cast_list.data
    m.genres = form.genres.data
    m.trailer = form.trailer.data

    db.session.commit()

    # Save picture / delete old one
    if form.picture.data:
        new_picture_name = save_picture(form.picture.data, 'movie', 'static', 'cover_arts')
        delete_picture('movie', 'static', 'cover_arts', m.cover_art_name)
        m.cover_art_name = new_picture_name

    flash(f'Movie \'{m.name}\' saved successfully', 'success')
    return redirect(url_for('movie.view_specific', movie_id=m.id))


# Probably should use flak-api or flask-restful idk?
@movies_blueprint.route('/hide', methods=['POST'])
@manager_permission.require(status.HTTP_401_UNAUTHORIZED)
def hide():
    form = SimpleForm()
    if not form.validate_on_submit():
        return get_json_response('Error hide movie failed', status.HTTP_400_BAD_REQUEST)

    m = Movie.query.get(form.id.data)
    if not m:
        return get_json_response(f'Movie with id \'{form.id.data}\' not found', status.HTTP_400_BAD_REQUEST)

    m.hidden = True
    db.session.commit()

    return get_json_response(f'Movie with id \'{form.id.data}\' successfully hidden', status.HTTP_200_OK)


# Probably should use flak-api or flask-restful idk?
@movies_blueprint.route('/show', methods=['POST'])
@manager_permission.require(status.HTTP_401_UNAUTHORIZED)
def show():
    form = SimpleForm()
    if not form.validate_on_submit():
        return get_json_response('Error show movie failed', status.HTTP_400_BAD_REQUEST)

    m = Movie.query.get(form.id.data)
    if not m:
        return get_json_response(f'Movie with id \'{form.id.data}\' not found', status.HTTP_400_BAD_REQUEST)

    m.hidden = False
    db.session.commit()

    return get_json_response(f'Movie with id \'{form.id.data}\' successfully unhidden', status.HTTP_200_OK)


@movies_blueprint.route('/manage', methods=['GET'])
@manager_permission.require(status.HTTP_401_UNAUTHORIZED)
def manage():
    movies = Movie.query.all()
    return render_template('manage_movie.html', title='Manage Movies', movies=movies)


@movies_blueprint.route('/search', methods=['POST'])
def search():
    form = SearchForm()
    if not form.validate_on_submit():
        return get_json_response('Search movie failed', status.HTTP_400_BAD_REQUEST)

    search_query = f'%{form.query.data}%'

    results = db.session.query(Movie.id, Movie.name).filter(
        Movie.name.like(search_query) | Movie.genres.like(search_query) | Movie.cast.like(search_query) |
        Movie.directors.like(search_query)) \
        .filter(~Movie.hidden) \
        .limit(5).all()

    movies = {m.name: m.id for m in results}
    return jsonify(movies)


@movies_blueprint.route('/search_results/')
def search_results():
    form = SearchResultsForm(request.args)
    if not form.validate_on_submit():
        pass

    search_query = f'%{form.query.data}%'

    results = db.session.query(Movie).filter(
        Movie.name.like(search_query) | Movie.genres.like(search_query) | Movie.cast.like(search_query) |
        Movie.directors.like(search_query)).filter(~Movie.hidden)\
        .all()

    return render_template('search_results.html', query=form.query.data, results=results)

Flask_Cinema_Site/user/views.py
from Flask_Cinema_Site import app, db, models, helper_functions
from Flask_Cinema_Site.models import User, Role
from Flask_Cinema_Site.helper_functions import get_redirect_url
from Flask_Cinema_Site.forms import SimpleForm
from .forms import LoginForm, SignupForm, ForgotPasswordForm, ResetPasswordForm, \
    ChangePasswordForm, ChangeDetailsForm

from flask import render_template, Blueprint, flash, redirect, url_for, request, current_app, session
from flask_login import LoginManager, login_user, logout_user, current_user, login_required
from flask_api import status
from flask_principal import identity_changed, Identity, AnonymousIdentity

from datetime import datetime

user_blueprint = Blueprint(
    'user', __name__,
    template_folder='templates'
)

login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_view = 'user.login'


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


def send_password_reset_email(user):
    token = user.get_reset_password_token()
    helper_functions.send_email(
        subject='[Microblog] Reset Your Password',
        sender=app.config['MAIL_USERNAME'],
        recipients=[user.email],
        text_body=render_template('email/reset_password_body.txt', user=user, token=token),
        html_body=render_template('email/reset_password_body.html', user=user, token=token)
    )


@app.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_password(token):
    u = User.verify_reset_password_token(token)
    if not u:
        flash('Invalid reset password link', 'danger')
        return redirect(get_redirect_url())

    form = ResetPasswordForm()
    if not form.validate_on_submit():
        return render_template('reset_password.html', form=form)

    u.set_password(form.password.data)
    db.session.commit()

    flash('Password updated successfully', 'success')
    return redirect(url_for('user.login_get'))


@user_blueprint.route('/forgot_password', methods=['GET', 'POST'])
def forgot_password():
    # Check if user logged in
    if current_user.is_authenticated:
        return redirect(get_redirect_url())

    form = ForgotPasswordForm()
    if request.method == 'GET':
        return render_template('forgot_password.html', title='Reset password', form=form)

    if not form.validate_on_submit():
        return render_template('forgot_password.html', title='Reset password', form=form), status.HTTP_400_BAD_REQUEST

    u = db.session.query(models.User).filter_by(email=form.email.data).first()
    if not u:
        flash('Unknown email has been entered.', 'danger')
        return render_template('forgot_password.html', title='Reset password', form=form)

    send_password_reset_email(u)
    flash('A link has been sent to your email to reset your password, the link will expire after 24 hours.', 'success')
    return render_template('forgot_password.html', title='Reset password', form=form)


@user_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    # Check if user logged in
    if current_user.is_authenticated:
        return redirect(get_redirect_url())

    form = LoginForm()
    if request.method == 'GET':
        return render_template('login.html', title='Login', form=form)

    # Validate form submission
    if not form.validate_on_submit():
        return render_template('login.html', title='Login', form=form), status.HTTP_400_BAD_REQUEST

    # Check for user
    u = User.query.filter_by(email=form.email.data).first()
    if not u or not u.check_password(form.password.data):
        flash('Login failed. Provided details were incorrect.', 'danger')
        return render_template('login.html', title='Login', form=form), status.HTTP_400_BAD_REQUEST

    # Update last login date time
    u.last_login = datetime.now()
    db.session.commit()

    # Login successful
    login_user(u, form.remember.data)
    # Tell Flask-Principal the identity changed
    identity_changed.send(current_app._get_current_object(), identity=Identity(u.id))

    flash('Login successful', 'success')
    return redirect(get_redirect_url())


@user_blueprint.route('/signup', methods=['GET', 'POST'])
def signup():
    # Check if user logged in
    if current_user.is_authenticated:
        return redirect(get_redirect_url())

    form = SignupForm()
    if request.method == 'GET':
        return render_template('signup.html', title='Sign Up', form=form)

    if not form.validate_on_submit():
        return render_template('signup.html', title='Sign Up', form=form), status.\
            HTTP_400_BAD_REQUEST

    new_user = models.User(first_name=form.first_name.data,
                           last_name=form.last_name.data,
                           username=form.username.data,
                           email=form.email.data,
                           confirmed=False)
    new_user.set_password(form.password.data)

    # Add user as customer
    customer_role = Role.query.filter_by(name='customer').first()
    customer_role.users.append(new_user)
    db.session.commit()

    # Generate and send confirmation email
    token = new_user.get_email_confirm_token()
    confirm_url = url_for('user.confirm_email', token=token, _external=True)

    helper_functions.send_email(
        subject='Confirm your account',
        sender=app.config['MAIL_USERNAME'],
        recipients=[new_user.email],
        text_body=render_template('email/confirm_email_body.txt', confirm_url=confirm_url),
        html_body=render_template('email/confirm_email_body.html', confirm_url=confirm_url)
    )

    flash(f'New user \'{new_user.username}\' was successfully created', 'success')
    return redirect(url_for('user.login'))


@user_blueprint.route('/confirm/<token>')
def confirm_email(token):
    u = User.verify_email_confirm_token(token)
    if u.confirmed:
        flash("Account already confirmed.", "danger")
        return redirect(url_for('home.home'))

    u.confirmed = True
    db.session.commit()
    flash(f'User \'{u.username}\' has been successfully confirmed', "success")
    return redirect(url_for('home.home'))


@login_required
@user_blueprint.route('/activate')
def activate():
    return render_template('verify_account.html')


@login_required
@user_blueprint.route('/resend')
def resend():
    # Generate and send confirmation email
    token = current_user.get_email_confirm_token()
    confirm_url = url_for('user.confirm_email', token=token, _external=True)
    helper_functions.send_email(
        subject='Confirm your account',
        sender=app.config['MAIL_USERNAME'],
        recipients=[current_user.email],
        text_body=render_template('email/confirm_email_body.txt', confirm_url=confirm_url),
        html_body=render_template('email/confirm_email_body.html', confirm_url=confirm_url)
    )
    flash("Activation link sent!", "warning")
    return redirect(url_for('user.activate'))


@user_blueprint.route('/logout', methods=['POST'])
def logout():
    if not current_user.is_authenticated:
        flash('Logout failed. No user logged in', 'danger')
        return redirect(get_redirect_url())

    form = SimpleForm()
    del form.id
    if not form.validate_on_submit():
        flash('Logout failed', 'danger')
        return redirect(url_for('home.home'))

    # Remove session keys set by Flask-Principal
    for key in ('identity.name', 'identity.auth_type'):
        session.pop(key, None)

    # Tell Flask-Principal the user is anonymous
    identity_changed.send(current_app._get_current_object(), identity=AnonymousIdentity())

    logout_user()
    flash('Logout successful', 'success')
    return redirect(url_for('home.home'))


def render_manage_user(change_details_form=None, change_password_form=None,
                       res_status=status.HTTP_200_OK):
    if change_details_form is None:
        change_details_form = ChangeDetailsForm()
        # Initialize form
        change_details_form.first_name.data = current_user.first_name
        change_details_form.last_name.data = current_user.last_name
        change_details_form.username.data = current_user.username
        change_details_form.email.data = current_user.email
    if change_password_form is None:
        change_password_form = ChangePasswordForm()

    return render_template('manage_user.html', title='Manage Account',
                           details_form=change_details_form,
                           password_form=change_password_form), res_status


@user_blueprint.route('/manage')
@login_required
# @check_confirmed if user makes mistake in email they cant fix it if they are required to confirm it first
def manage():
    return render_manage_user()


@user_blueprint.route('/manage/update_user_details', methods=['POST'])
@login_required
def update_user_details():
    form = ChangeDetailsForm()

    # Validate submitted details
    if not form.validate_on_submit():
        return render_manage_user(change_details_form=form, res_status=status.HTTP_400_BAD_REQUEST)

    # Update details
    current_user.confirmed = current_user.confirmed and current_user.email == form.email.data
    current_user.first_name = form.first_name.data
    current_user.last_name = form.last_name.data
    current_user.username = form.username.data
    current_user.email = form.email.data
    db.session.commit()

    flash('Details successfully updated', 'success')

    return render_manage_user(change_details_form=form)


@user_blueprint.route('/manage/change_password', methods=['POST'])
@login_required
def change_password():
    form = ChangePasswordForm()

    if not form.validate_on_submit():
        return render_manage_user(change_password_form=form, res_status=status.HTTP_400_BAD_REQUEST)

    # Update password
    current_user.set_password(form.password.data)
    db.session.commit()
    flash('Password updated successfully', 'success')
    return render_manage_user(change_password_form=form)

Flask_Cinema_Site/templates/snippets/cookie_warning.html
<!-- Cookie warning toast -->
<div class="fixed-bottom bg-black d-none" id="cookieAlert">
    <div class="toast bg-dark-purple text-white w-100" role="alert" data-autohide="false">
        <div class="toast-body p-4 d-flex flex-column container">
            <h4>Cookie Warning</h4>
            <p>This website uses persistent cookies to
            </p>
            <ul>
                <li>enable login remember me functionality</li>
                <li>remember cookie preferences (stop this annoying you each session)</li>
            </ul>
            <p>Non-persistent cookies are to remember choice.</p>
            <div class="ml-auto">
                <button type="button" class="btn btn-outline-light mr-3" id="cookieDeny">Deny</button>
                <button type="button" class="btn btn-success" id="cookieAccept">Accept</button>
            </div>
        </div>
    </div>
</div>

Flask_Cinema_Site/templates/snippets/footer.html
<footer class="text-muted">
    <div class="container">
        <p class="float-right">
            <a href="#">Back to top</a>
        </p>
        <p>Copyright © Group 40 2020</p>
    </div>
</footer>

Flask_Cinema_Site/templates/snippets/nav.html
<nav class="navbar navbar-expand-lg navbar-dark mb-4">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="container">
        <div class="collapse navbar-collapse" id="navbarContent">
            <!-- Nav bar left -->
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="navbar-brand d-flex" href="{{ url_for('home.home') }}">
                        <span class="movie_box">Moviebox</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('movie.view_multiple') }}">Browse Movies</a>
                </li>
            </ul>

            <div class="mr-2">
                <form class="form-inline input-group" action="{{ url_for('movie.search_results') }}" method="GET">
                    <input class="form-control" type="search" placeholder="Search" aria-label="Search" name="query"
                           id="searchBox">
                    <div class="input-group-append">
                        <div class="input-group-text p-0">
                            <button class="btn" type="submit" value="search_results">
                                <i class="bi bi-search"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>

            <!-- Nav bar right -->
            <ul class="nav navbar-nav navbar-right">
                {% if is_manager() %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="managementDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Cinema Management
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="managementDropdown">
                            {% if is_admin() and config['ENV'] == 'development' %}
                                <a class="dropdown-item" href="{{ url_for('admin.index') }}">Admin</a>
                                <div class="dropdown-divider"></div>
                            {% endif %}
                            <a class="dropdown-item" href="{{ url_for('movie.add') }}">Add new movie</a>
                            <a class="dropdown-item" href="{{ url_for('movie.manage') }}">Manage movie</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{{ url_for('analysis.view_multiple') }}">View analysis</a>
                        </div>
                    </li>
                {% endif %}

                {% if current_user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{ current_user.username }}
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                            <a class="dropdown-item" href="{{ url_for('bookings.my_upcoming_bookings') }}">My Bookings</a>
                            <a class="dropdown-item" href="{{ url_for('user.manage') }}">Manage Account</a>
                            <div class="dropdown-divider"></div>
                            <form action="{{ url_for('user.logout') }}" method="post">
                                {{ simple_form.csrf_token(id="logoutCsrfToken") }}
                                <button class="dropdown-item" type="submit">Logout</button>
                            </form>
                        </div>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('user.login', next=request.path) }}">Login</a>
                    </li>
                    <li class="nav-item"><a class="nav-link" href="{{ url_for('user.signup') }}">Register</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>